### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by blachniet** [blachniet/new-images-inc#1]
- [ ] Web app manifest ([MDN][1])
- [ ] Populate open graph meta (e.g. `og:title`, `og:type`)
- [ ] Add apple-touch-icon
- [ ] Add favicon
- [ ] Set [theme-color meta][2] ([MDN][3])
- [ ] Configure Google Analytics
- [ ] Get domain name
- [ ] Shrink image sizes

[1]: https://developer.mozilla.org/en-US/docs/Web/Manifest
[2]: https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L22
[3]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
